# Generated by Django 6.0 on 2026-06-16 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useritem_subtotal_useritem_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserItem',
            new_name='Cart',
        ),
    ]
